### ISSUE TITLE
polypoly::poly_add_columns fails if column has NA

### ISSUE THREAD

**Issue by kendonB** [tjmahr/polypoly#2]
``` r
library(polypoly)
iris$Sepal.Length[1] <- NA_real_
poly_add_columns(iris, Sepal.Length)
#> Warning: Prefixing `UQS()` with the rlang namespace is deprecated as of rlang 0.3.0.
#> Please use the non-prefixed form or `!!!` instead.
#> 
#>   # Bad:
#>   rlang::expr(mean(rlang::UQS(args)))
#> 
#>   # Ok:
#>   rlang::expr(mean(UQS(args)))
#> 
#>   # Good:
#>   rlang::expr(mean(!!!args))
#> 
#> This warning is displayed once per session.
#> Error: New columns in `add_column()` must be consistent with `.data`:
#> * `.data` has 150 rows
#> * New column contributes 149 rows
```

<sup>Created on 2020-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tjmahr** [comment]
Thanks for opening the issue. What do you think it should it do?

**Comment by tjmahr** [comment]
My guess would be to `warn()`, try to create the polynomial basis with the other values and let the NAs propagate to the added columns.

**Comment by kendonB** [comment]
Agree that there should be a warning here. Just need to be careful that the numbers and NAs actually end up in the right place

**Comment by mvuorre** [comment]
I think its fair to fail informatively (?) since polypoly uses poly() for the calculation which doesn't allow missingness in x.
