### ISSUE TITLE
rlang warning fixed in GitHub, but not updated in CRAN

### ISSUE THREAD

**Issue by mlaviolet** [tjmahr/polypoly#4]
The rlang warning referenced in issue #1 was fixed in the GitHub version of the package (0.0.2.9000) but not updated in CRAN. Could you update? Thanks!

**Comment by tjmahr** [comment]
Thanks for the issue. I will have to update the package testing for the submission to get rid of the Travis stuff and use Github actions.

**Comment by mlaviolet** [comment]
Thanks!
